name: Check code style

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  code-style:
    name: Pint (portavice config)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, mbstring, pdo_sqlite, sqlite3, tokenizer, gd, exif, zip, fileinfo
          coverage: none
      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress
      - name: Check code style
        run: composer cs
